# Generated by Django 4.1.1 on 2022-09-24 04:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500, validators=[django.core.validators.URLValidator(schemes=('http', 'https'))], verbose_name='リンク')),
                ('search_word', models.CharField(max_length=200, verbose_name='検索したワード')),
                ('description', models.TextField(blank=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IPアドレス')),
                ('good_count', models.IntegerField(default=0, verbose_name='いいね数')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
    ]
