# Generated by Django 4.1.1 on 2022-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_remove_tag_post'),
        ('posts', '0003_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
