# Generated by Django 4.1.1 on 2022-10-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='コメント'),
        ),
    ]
