# Generated by Django 4.1.1 on 2022-09-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_post_alter_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
    ]
